apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  namespace: blog-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
        - name: blog-backend
          image: 123456789.dkr.ecr.ap-northeast-2.amazonaws.com/blog-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: blog-backend