apiVersion: v1
kind: Service
metadata:
  name: blog-backend
  namespace: blog-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: blog-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080